config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  root to: 'homes#top'
  get 'home/about' => "homes#about"
  #get '/users'=> "users#index"
  resources :users, only: [:show,:index, :edit, :update] do
    resource :relationships, only: [:create, :destroy]
    get "follower" => "relationships#follower", as: "follwer"
    get "followed" => "relationships#followed", as: "follwed"
  end

  resources :books, only: [:new, :index, :show, :edit,:create,:destroy,:update] do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only:[:create, :destroy]
  end

  resources :groups, only: [:new, :index, :show, :edit, :create, :destroy, :update] do
    resource :group_users, only: [:create, :destroy]
    get "new_mail" => "groups#new_mail", as: "new_mail"
    get "send_mail" => "groups#send_mail", as: "send_mail"
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :group_users, dependent: :destroy
  has_many :users, through: :group_users

  has_one_attached :image

  def get_group_image
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/group_image.jpg')
      image.attach(io: File.open(file_path), filename: 'group_image.jpg')
    end
    image
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :is_match_login_user, only: [:edit, :create]

  def index
    @groups = Group.all
  end

  def new
    @group = Group.new
  end

  def show
    @group = Group.find(params[:id])
    @group_user = @group.users
  end

  def edit
    @group = Group.find(params[:id])
  end

  def create
    group = Group.new(group_params)
    group.owner_id = current_user.id
    group.save
    redirect_to groups_path
  end

  def destroy
  end

  def update
    group = Group.find(params[:id])
    group.update(group_params)
    redirect_to groups_path
  end

  #メール
  def new_mail
    @group = Group.find(params[:group_id])
  end

  def send_mail
    @group = Group.find(params[:group_id])
    group_users = @group.users
    @mail_title = params[:mail_title]
    @mail_content = params[:mail_content]
    OwnerMailer.send_mail(@mail_title, @mail_content, group_users).deliver_now
  end


  private
  def group_params
    params.require(:group).permit(:name, :introduction, :image) 
  end

  def is_match_login_user
    group = Group.find(params[:id])
    unless group.owner_id == current_user.id
      redirect_to groups_path
    end
  end
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/_form.html.erb
<%= form_with model: group do |f| %>
  <%= f.label :name, "グループ名" %><br>
  <%= f.text_field :name %><br>

  <%= f.label :introduction, "紹介文" %><br>
  <%= f.text_area :introduction %><br>

  <%= f.label :image,"グループ画像" %><br>
  <%= f.file_field :image %><br>

  <%= f.submit "Create Group", class:"btn btn-success mt-3" %>
<% end %>

app/views/groups/edit.html.erb
<div class="container">
  <div class="row justify-content-center">
    <h3>Edit Group</h3>
  </div>

  <div class="row justify-content-center">
    <%= render "form", group: @group %>
  </div>
</div>

app/views/groups/index.html.erb
<div class="container">

  <div class="row">

    <div class="col-3">
      <%= render "books/userinfo", user: current_user %> 
    </div>


    <div class="col-8 offset-1">
      <h2>Groups</h2>
      <table class="table">
        <thead>
          <tr>
            <th></th>
            <th>グループ名</th>
            <th>紹介文</th>
            <th>メンバー数</th>
            <th></th>
          </tr>
        </thead>

        <tbody>
          <% @groups.each do |group| %>
          <tr>
            <td>
              <%= image_tag group.get_group_image.variant(resize_to_limit: [100, 100]).processed %>
            </td>
            <td>
              <%= link_to group_path(group.id) do %>
                <%= group.name %>
              <% end %>
            </td>
            <td><%= group.introduction %></td>
            <td><%= group.users.count %></td>
            <td>
              <% if group.owner_id == current_user.id %>
                <%= link_to "Edit", edit_group_path(group.id), class: "btn btn-success" %>
              <% end %>
            </td>
          </tr>
          <% end %>
        </tbody>
      </table>
    
    </div>
  
  </div>

</div>

app/views/groups/new.html.erb
<div class="container">
  <div class="row justify-content-center">
    <h3>Create Group</h3>
  </div>

  <div class="row justify-content-center">
    <%= render "form", group: @group %>
  </div>
</div>

app/views/groups/new_mail.html.erb
<div class="container">
  <div class="row justify-content-center">
    <h2>Event Mail</h2>
  </div>
  <div class="row justify-content-center">
    <%= form_with url:group_send_mail_path(@group), method: :get do |f| %>

      <%= f.label :mail_title, "タイトル", class:"mt-2" %><br>
      <%= f.text_field :mail_title, class: "form-control" %>
      <br>
      <%= f.label :mail_content, "本文", class:"mt-2" %><br>
      <%= f.text_area :mail_content, class:"form-control" %>
      <br>
      <%= f.submit "送信", class:"btn btn-success mt-2" %>

    <% end %>
  </div>
</div>

app/views/groups/send_mail.html.erb
<div class="container">
  <div class="row">
    <div class="col offset-4">
      <h2>送信が完了しました</h2>
      <p>内容は以下の通りです。</p>

      <div>
        [タイトル]
        <p><%= @mail_title %></p>
      </div>

      <div>
        [本文]
        <p><%= @mail_content %></p>
      </div>
    </div>
  </div>
</div>

app/views/groups/show.html.erb
<div class="container">

  <div class="row">

    <div class="col-3">
      <%= render "books/userinfo", user: current_user %> 
    </div>


    <div class="col-8 offset-1">
      <h2>Groups Detail</h2>
      <table class="table">
        <thead>
          <tr>
            <th></th>
            <th>グループ名</th>
            <th>紹介文</th>
            <th>メンバー</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td>
              <%= image_tag @group.get_group_image.variant(resize_to_limit: [100, 100]).processed %>
            </td>
            <td>
              <%= link_to group_path(@group.id) do %>
                <%= @group.name %>
              <% end %>
            </td>
            <td><%= @group.introduction %></td>
            <td>
              <% @group_user.each do |group_user| %>
                <%= group_user.name %><br>
              <% end %>
            </td>
            <% if @group.owner_id == current_user.id %>
              <td><%= link_to "Edit", edit_group_path(@group.id), class: "btn btn-success" %></td>
              <td><%= link_to "Notice an Event", group_new_mail_path(@group.id), class: "btn btn-info" %></td>
            <% else %>
              <td>
                <% if @group.group_users.exists?(user_id: current_user.id) %>
                  <%= link_to "Leave this group", group_group_users_path(@group.id), method: :delete, class: "btn btn-danger" %>
                <% else %>
                  <%= link_to "Join this group", group_group_users_path(@group.id), method: :post, class: "btn btn-success" %>
                <% end %>
              </td>
              <td></td>
            <% end %>
          </tr>
        </tbody>
      </table>
    
    </div>
  
  </div>

</div>