config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  root to: 'homes#top'
  get 'home/about' => "homes#about"
  #get '/users'=> "users#index"
  resources :users, only: [:show,:index, :edit, :update] do
    resource :relationships, only: [:create, :destroy]
    get "follower" => "relationships#follower", as: "follwer"
    get "followed" => "relationships#followed", as: "follwed"
  end

  resources :books, only: [:new, :index, :show, :edit,:create,:destroy,:update] do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only:[:create, :destroy]
  end

  resources :groups, only: [:new, :index, :show, :edit, :create, :destroy, :update] do
    resource :group_users, only: [:create, :destroy]
    get "new_mail" => "groups#new_mail", as: "new_mail"
    get "send_mail" => "groups#send_mail", as: "send_mail"
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, uniqueness: true, length: { in: 2..20 }
  validates :introduction, length: { maximum: 50 }

  has_one_attached :image

  has_many :books, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  #フォロー機能
  #フォローしている
  has_many :follower, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :following, through: :follower, source: :followed
  #フォローされた
  has_many :followed, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :followers, through: :followed, source: :follower

  #グループ
  has_many :group_users, dependent: :destroy
  has_many :groups, through: :group_users

  has_one_attached :profile_image

  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [width, height]).processed
  end

  def follow_by?(user)
    following.include?(user)
  end

  def follow(user)
    unless self == user
      follower.create(followed_id: user.id)
    end
  end

  def unfollow(user)
    follower.find_by(followed_id: user.id).destroy
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :is_match_login_user, only:[:edit, :update]

  def show
    @user = User.find(params[:id])
    @books = @user.books
    @book = Book.new
    @hon = Book.new #エラー用
    #投稿数 計測
    @today_books = @books.created_today
    @yesterday_books = @books.created_one_ago
    @this_week_books = @books.created_this_week
    @last_week_books = @books.created_last_week

    #7日分の投稿数
    @two_ago_books = @books.created_two_ago
    @three_ago_books = @books.created_three_ago
    @four_ago_books = @books.created_four_ago
    @five_ago_books = @books.created_five_ago
    @six_ago_books = @books.created_six_ago 
  end

  def edit
    @user = User.find(params[:id])

  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "Book was successfully updated."
      redirect_to user_path(@user.id)
    else
      render :edit
    end
  end

  def index
    @users = User.all
    @books = Book.all
    @book = Book.new
    @hon = Book.new #エラー用
  end

  def search
    @user = User.find(params[:user_id])
    @books = @user.books
    @book = Book.new

    if params[:created_at] == ""
      @search_book = "日付を選択してね"
    else
      create_at = params[:created_at]
      @search_book = @books.where(['created_at LIKE ? ', "#{create_at}%"]).count
    end
  end


  private

  def user_params
    params.require(:user).permit(:name,:introduction,:profile_image)
  end

  def is_match_login_user
    user = User.find(params[:id])
    unless user.id == current_user.id
      redirect_to user_path(current_user.id)
    end
  end



end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_search.html.erb
<h4>検索結果</h4>
<table class="table">
  <thead>
    <tr>
      <th>投稿数</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><%= search_book %></td>
    </tr>
  </tbody>
</table>

app/views/users/edit.html.erb
    
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      
      <h2>User info</h2>
      
      <!--エラーメッセージ -->
      <% if @user.errors.any? %>
        <h3> 
        <%= @user.errors.count %> errors prohibited this obj from being saved:
        </h3>
        <ul>
          <% @user.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      <% end %>
      
      <%= form_with model: @user do |f| %>
      
      <div class="form-group">
        <p for="inputName">Name</p>
        <%= f.text_field :name, autofocus: true, id:"inputName" %>
      </div>
      
      <div class="form-group">
        <p for="inputImage">Image</p>
        <%= f.file_field :profile_image, placeholder: "プロフィール画像", accept: "image/*" %>
      </div>
        
      <div class="form-group">
        <p for="inputIntroduction">introduction</p>
        <%= f.text_area :introduction, autofocus: true %>
      </div>
      
      <div class="form-group">
          <button type="submit" class="btn btn-secondary">
            Update User
          </button>
        </div>
        
      <% end %>
      
    </div>
  </div>
</div>    

app/views/users/index.html.erb
<!--User一覧-->

<div class="container px-5">
  <div class="row">
     <!-- User info -->
    <div class="col-md-3">
      <%= render "books/userinfo", user: current_user %>
    </div>

    <!--user一覧-->
    <div class="col-md-8 offset-md-1">
    <h2>Users</h2>
    <p>
      <%= link_to "グループの作成", new_group_path %>
      |
      <%= link_to "グループ一覧", groups_path %>
    </p>
      <table class="table table-hover table-inver">
      <thead>
        <tr>
          <th><h4>image</h4></th>
          <th><h4>name</h4></th>
          <th></th>
          <th></th>
          <th></th>
          <th></th>
        </tr>
      </thead>

      <tbody>
        <% @users.each do |user| %>
        <tr>
          <td><p><span><%= image_tag user.get_profile_image(100,100) %></span></p></td>
          <td><p><span><%= user.name %></span></p></td>
          <td>フォロー数：<%= user.following.count %></td>
          <td>フォロワー数：<%= user.followers.count %></td>
          <td>
            <% unless user == current_user %>
              <% if current_user.follow_by?(user) %>
                <%= link_to "フォロー解除", user_relationships_path(user.id), method: :delete %>
              <% else %>
                <%= link_to "フォロー", user_relationships_path(user.id), method: :post %>
              <% end %>
            <% end %>
          </td>
          <td><%= link_to "Show", user_path(user.id)%></td>
        </tr>
        <% end %>
      </tbody>
      </table>
    </div>

  </div>
</div>

app/views/users/search.js.erb
$('#search_result').html("<%= j(render 'search', search_book: @search_book ) %>");

app/views/users/show.html.erb
<!--Home-->

<div class="container px-5">
  <div class="row">
     <!-- User info -->
    <div class="col-md-3">
      <%= render "books/userinfo", user: @user %>
    </div>

    <!--book一覧-->
    <div class="col-md-8 offset-md-1">
    <h2>Books</h2>
      <table class="table table-hover table-inverse">
      <thead>
        <tr>
        <th></th>
        <th><h4>Title</h4></th>
        <th><h4>Opinion</h4></th>
        <th><h5>Comment</h5></th>
        <th><h5><i class="fa-solid fa-heart"></i></h5></th>

        </tr>
      </thead>

      <tbody>
        <% @books. each do |book| %>
        <tr>
          <td>
          <%= link_to user_path(@user.id) do %>
            <%= image_tag book.user.get_profile_image(100,100) %>
          <% end %>
          </td>
          <td>
          <%= link_to book_path(book.id) do %>
              <%= book.title %>
              <% end %>
          </td>
          <td><p><span><%= book.body %></span></p></td>

          <td>
          <p><%= link_to "#{book.book_comments.count} コメント", book_path(book.id) %></p>
          </td>

          <td>
          <% if book.favorited_by?(current_user) %>
            <p>
              <%= link_to book_favorites_path(book), method: :delete do %>
                <button type="button" class="btn btn-outline-primary">
                  <i class="fa-solid fa-heart"></i>
                </button>
                <br>
                <%= book.favorites.count %>
                いいね
              <% end %>
            </p>
          <% else %>
            <p>
              <%= link_to book_favorites_path(book), method: :post do %>
                <button type="button" class="btn btn-outline-primary">
                  <i class="fa-regular fa-heart"></i>
                </button>
                <br>
                <%= book.favorites.count %>
                いいね
              <% end %>
            </p>
          <% end %>
          </td>

        </tr>
        <% end %>
      </tbody>
      </table>

      <hr>
      <h3>投稿の前日比・先週比</h3>
      <table class="table">
        <tr>
          <th>今日の投稿数</th>
          <th>前日の投稿数</th>
          <th>前日比</th>
        </tr>
        <tr>
          <td><%= @today_books.count %></td>
          <td><%= @yesterday_books.count %></td>
          <td>
            <% if @yesterday_books.count == 0 %>
              前日の投稿なし
            <% else %>
              <%= @today_books.count %> / <%= @yesterday_books.count %>
            <% end %>
          </td>
        </tr>
        <tr>
          <th>今週の投稿数</th>
          <th>先週の投稿数</th>
          <th>先週比</th>
        </tr>
        <tr>
          <td><%= @this_week_books.count %></td>
          <td><%= @last_week_books.count %></td>
          <td>
            <% if @last_week_books.count == 0 %>
              先週の投稿なし
            <% else %>
              <%= @this_week_books.count %> / <%= @last_week_books.count %>
            <% end %>
          </td>
        </tr>
      </table>

      <hr class="mt-3">
      <h3>7日分の投稿数</h3>
      <table class="table table-bordered">
        <tr>
          <th>6日前</th>
          <th>5日前</th>
          <th>4日前</th>
          <th>3日前</th>
          <th>2日前</th>
          <th>1日前</th>
          <th>今日</th>
        </tr>
        <tr>
          <td><%= @six_ago_books.count %></td>
          <td><%= @five_ago_books.count %></td>
          <td><%= @four_ago_books.count %></td>
          <td><%= @three_ago_books.count %></td>
          <td><%= @two_ago_books.count %></td>
          <td><%= @yesterday_books.count %></td>
          <td><%= @today_books.count %></td>
        </tr>
      </table>

      <hr class="mt-3">
      <canvas id="myLineChart"></canvas>
      <script>
        $(document).on('turbolinks:load', function() {
          var ctx = document.getElementById("myLineChart");
          var myLineChart = new Chart(ctx, {
            type: 'line',
            data: {
              labels: ['6日前', '5日前', '4日前', '3日前', '2日前', '1日前', '今日'],
              datasets: [
                {
                  label: '投稿した本の数',
                  data: [
                    <%= @books.created_six_ago.count %>,
                    <%= @books.created_five_ago.count %>,
                    <%= @books.created_four_ago.count %>,
                    <%= @books.created_three_ago.count %>,
                    <%= @books.created_two_ago.count %>,
                    <%= @books.created_one_ago.count %>,
                    <%= @books.created_today.count %>
                  ],
                  borderColor: "rgba(0,0,255,1)",
                  backgroundColor: "rgba(0,0,0,0)",
                  tension: 0.4
                }
              ],
            },
            options: {
              title: {
                display: true,
                text: '7日間の投稿数の比較'
              },
              responsive: true,
              scales: {
                y:{
                  suggestedMin: 0,
                  suggestedMax: 10
                },
                x:{
                  stacked: true
                },
              },
            }
          });
        });
      </script>


      <hr class="mt-3">
      <h3>投稿数検索</h3>
      <%= form_with url: user_search_path(@user.id), method: :get, local: false do |f| %>
        <%= f.date_field :created_at %>
        <%= f.submit "検索", class:"btn btn-primary" %>
      <% end %>

      <div id="search_result">
        <% if @search_book.present? %>
          <%= render "search", search_book: @search_book %>
        <% end %>
      </div>

    </div>
  </div>
</div>