config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  root to: 'homes#top'
  get 'home/about' => "homes#about"
  #get '/users'=> "users#index"
  resources :users, only: [:show,:index, :edit, :update] do
    resource :relationships, only: [:create, :destroy]
    get "follower" => "relationships#follower", as: "follwer"
    get "followed" => "relationships#followed", as: "follwed"
  end

  resources :books, only: [:new, :index, :show, :edit,:create,:destroy,:update] do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only:[:create, :destroy]
  end

  resources :groups, only: [:new, :index, :show, :edit, :create, :destroy, :update] do
    resource :group_users, only: [:create, :destroy]
    get "new_mail" => "groups#new_mail", as: "new_mail"
    get "send_mail" => "groups#send_mail", as: "send_mail"
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/book.rb
class Book < ApplicationRecord

  validates :title, presence: true
  validates :body, presence: true, length: { maximum: 200 }
  validates :tag, presence: true

  belongs_to :user
  has_many :book_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def new
    @book = Book.new
  end

  def create
     @hon = Book.new(book_params)
     @hon.user_id = current_user.id

     if @hon.save
      flash[:notice] = "Book was successfully created."
      #@hon = book.new(book_params)
      redirect_to book_path(@hon.id)
     else
      #flash[:notice] = "失敗しちゃったよ"
      @books = Book.all.order(params[:sort])
      @book = Book.new
      render :index
     end
  end

  def index
    if params[:category].present?
      @books = Book.where(tag: params[:category])
    else
      @books = Book.all.order(params[:sort])
    end

    @book = Book.new
    @hon = Book.new #エラー用
  end

  def show
    @book = Book.find(params[:id])
    @book_user = @book.user
    #@books = Book.all
    @book_comment = BookComment.new
  end

  def edit
    is_match_login_user
    @book = Book.find(params[:id])
    @hon = Book.find(params[:id]) #エラー用
  end

  def update
    is_match_login_user
    @hon = Book.find(params[:id])

    if @hon.update(book_params)
      @book = Book.find(params[:id])
      flash[:notice] = "Book was successfully updated."
      redirect_to book_path(@book.id)
    else
      #flash[:notice] = "Book was not successfully updated"
      @book =  Book.find(params[:id])
      render :edit

    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy

    if @book.destroy
      flash[:notice] = "Book was successfully delete."
      redirect_to books_path
    else
      flash[:notice] = "消せなかったよ"
      redirect_to books_path
    end

  end

  private
    def book_params
      params.require(:book).permit(:title, :body, :image, :star, :tag)
    end

  def is_match_login_user
    book = Book.find(params[:id])
    unless book.user_id == current_user.id
      redirect_to "/books"
    end
  end


end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_star_rate.html.erb
<div id="star_<%= book.id %>"></div>
<script>
        $(document).on('turbolinks:load', function() {
        let elem = document.querySelector('#star_<%= book.id %>');
        if(elem == null) return;

        elem.innerHTML = ""
        let opt = {
          starOn: "<%= asset_path('star-on.png') %>",
          starOff: "<%= asset_path('star-off.png') %>",
          starHalf: "<%= asset_path('star-half.png') %>",
          score: "<%= book.star %>",
          readOnly: true,
        };
        raty(elem, opt);
      });
</script>

app/views/books/_userinfo.html.erb
<h3>User info</h3>
<%= image_tag user.get_profile_image(100,100) %>
<table class="table table-hover table-inverse">
  <tbody>
    <tr>
      <td><p>name</p></td>
      <td><p><span><%= user.name %></span></p></td>
    </tr>
    <tr>
      <td><p>introduction</p></td>
      <td><p><span><%= user.introduction %></span></p></td>
    </tr>
    <tr>
      <th><p>フォロー中</p></th>
      <td>
        <%= link_to user_follwer_path(user.id) do %>
          <%= user.following.count %>
        <% end %>
      </td>
    </tr>
    <tr>
      <th><p>フォロワー</p></th>
      <td>
        <%= link_to user_follwed_path(user.id) do %>
          <%= user.followers.count %>
        <% end %>
      </td>
    </tr>
  </tbody>
</table>

<!--User 編集-->
<% if user == current_user %>
  <%= link_to  edit_user_path(user.id) do %>
  <button type="button" class="btn btn-outline-secondary btn-block">
    <i class="fas fa-user-cog"></i>
  </button>
  <% end %>
<% else %>
  <% if current_user.follow_by?(user) %>
    <%= link_to "フォロー解除", user_relationships_path(user.id), method: :delete, class:"btn btn-info" %>
  <% else %>
    <%= link_to "フォローする", user_relationships_path(user.id), method: :post, class:"btn btn-success" %>
  <% end %>
<% end %>

<!--新規作成 -->
<div class="New book mt-3">
  <h3>New book</h3>
  <%= form_with model: Book.new do |f| %>
    <%= f.label :title, "Title" %><br>
    <%= f.text_field :title %>
    <br>
    <%= f.label :body, "Opinion" %><br>
    <%= f.text_area :body %>

    <!--★評価-->
    <div class="form-group" id="star">
      <%= f.label :star %>
      <%= f.hidden_field :star, id: :review_star, class: "form-control" %>
      <div id="post_raty"></div>
    </div>
    <script>
      $(document).on('turbolinks:load', function() {
        let elem = document.querySelector('#post_raty');
        if(elem == null) return;

        elem.innerHTML = ""
        let opt = {
          starOn: "<%= asset_path('star-on.png') %>",
          starOff: "<%= asset_path('star-off.png') %>",
          starHalf: "<%= asset_path('star-half.png') %>",
          scoreName: 'book[star]',
        };
        raty(elem, opt);
      });
    </script>

    <br>
    <%= f.label :tag, "Tag" %><br>
    <%= f.text_field :tag %>

    <div class="submit mt-2">
      <%= f.submit "Create Book", class: "btn btn-success" %>
    </div>
  <% end %>
</div>

app/views/books/edit.html.erb
 <%= form_with model: @book do |f| %>
  <div class="container">
    <div class="row">
      <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">

        <h1>Editing Book</h1>

         <!--エラーメッセージ-->
         <% if @hon.errors.any? %>
            <h3>
            <%= @hon.errors.count %> errors prohibited this obj from being saved:
            </h3>
            <ul>
              <% @hon.errors.full_messages.each do |message| %>
               <li><%= message %></li>
              <% end %>
             </ul>
         <% end %>

        <div class="form-group">
          <p>Title</p>
          <%= f.text_field :title %>
        </div>

        <div class="form-group">
          <p>Opinion</p>
          <%= f.text_area :body %>
        </div>

        <div class="form-group">
          <button type="submit" class="btn btn-success">
            Update Book
          </button>
        </div>

        <%= link_to "Show", book_path(@book.id)%>
        <a>|</a>
        <%= link_to "Back", '/books' %>

      </div>
    </div>
  </div>


  <% end %>

app/views/books/index.html.erb
<!--Books-->
<div class="container px-5">

  <!--検索-->
  <%= form_with url: books_path, method: :get do |f| %>
    <%= f.text_field :category %>
    <%= f.submit "検索" %>
  <% end %>

  <!--新規作成のエラーメッセージ -->

    <% if @hon.errors.any? %>

    <h3>
    <%= @hon.errors.count %> errors prohibited this obj from being saved:
    </h3>
     <ul>
      <% @hon.errors.full_messages.each do |message| %>
       <li><%= message %></li>
      <% end %>
     </ul>
    <% end %>

  <div class="row">
    <div class="col-md-3">
      <!--共通-->
      <%= render 'userinfo' , user: current_user %>
      <!--共通-->
    </div>

    <div class="col-md-8 offset-md-1">
      <h2>Books</h2>
      <%= link_to "新しい順", books_path(sort: 'created_at DESC') %> 
      |
      <%= link_to "評価の高い順", books_path(sort: 'star DESC') %>
      <table class="table table-hover table-inverse">
      <thead>
        <tr>
          <th></th>
          <th><h4>Title</h4></th>
          <th><h4>Opinion</h4></th>
          <th><h5>Tag</h5></th>
          <th><h5>Comment</h5></th>
          <th><h5><i class="fa-solid fa-heart"></i></h5></th>
          <th></th>
        </tr>
      </thead>

      <tbody>
        <% @books.each do |book| %>
        <tr>
          <td>
          <%= link_to user_path(book.user.id) do %>
            <%= image_tag book.user.get_profile_image(100,100) %>
          <% end %>
          </td>
          <td>
          <%= link_to  book_path(book.id) do %>
            <%= book.title %>
          <% end %>
          </td>
          <td><p><span><%= book.body %></span></p></td>

          <td>
            <%= link_to books_path(category: book.tag) do %>
              <%= book.tag %>
            <% end %>
          </td>

          <td>
            <p><%= link_to "#{book.book_comments.count} コメント", book_path(book.id) %></p>
          </td>

          <td id="favorite-btn-<%= book.id %>">
            <%= render "favorites/favorite-btn", book:book %>
          </td>

          <td>
            <%= render "star_rate", book: book %>
          </td>

        </tr>
        <% end %>
      </tbody>
      </table>
    </div>
  </div>
</div>

app/views/books/show.html.erb
<!--Books detail-->

<div class="container px-5">
 <div class="row">
  <div class="col-md-3">

<!--共通-->
<%= render 'userinfo', user: @book_user %>
<!--共通-->

  </div>

     <!--book一覧-->
  <div class="col-md-8 offset-md-1">
   <h2>Book detail</h2>
    <table class="table table-hover table-inverse">
      <tbody>
        <tr>
          <td>
               <%= link_to user_path(@book.user.id) do %>
                <%= image_tag @book.user.get_profile_image(100,100) %>
                <br>
                <%= @book.user.name %>
               <% end %>
          </td>

          <td>
           <%= link_to book_path do %>
             <%= @book.title %>
           <% end %>
          </td>

          <td><p><span><%= @book.body %></span></p></td>

          <td><%= @book.tag %></td>

          <td id="favorite-btn-<%= @book.id %>">
            <%= render "favorites/favorite-btn", book:@book %>
          </td>

          <td id="comment-count" >
            <%= render "book_comments/comment_count", book:@book %>
          </td>

          <td>
            <%= render "star_rate", book: @book %>
          </td>

          <% if @book.user == current_user %>
          <td>
            <%= link_to  edit_book_path(@book.id) do %>
            <button type="button" class="btn btn-success">Edit</button>
            <% end %>
          </td>

          <td>
            <%= link_to book_path(@book.id),method: :delete, "data-confirm" => "Are you sure？" do %>
            <button type="button" class="btn btn-danger">Destroy</button>
            <% end %>
          </td>
          <% end %>
        </tr>

      </tbody>
    </table>

    <hr>

    <!--コメント-->
    <div id="comment-index">
      <%= render "book_comments/comment_index", book: @book %>
    </div>
    <%= render "book_comments/comment_form", book: @book, book_comment: @book_comment %>


  </div>