config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  root to: 'homes#top'
  get 'home/about' => "homes#about"
  #get '/users'=> "users#index"
  resources :users, only: [:show,:index, :edit, :update] do
    resource :relationships, only: [:create, :destroy]
    get "follower" => "relationships#follower", as: "follwer"
    get "followed" => "relationships#followed", as: "follwed"
  end

  resources :books, only: [:new, :index, :show, :edit,:create,:destroy,:update] do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only:[:create, :destroy]
  end

  resources :groups, only: [:new, :index, :show, :edit, :create, :destroy, :update] do
    resource :group_users, only: [:create, :destroy]
    get "new_mail" => "groups#new_mail", as: "new_mail"
    get "send_mail" => "groups#send_mail", as: "send_mail"
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord

  validates :title, presence: true
  validates :body, presence: true, length: { maximum: 200 }
  validates :tag, presence: true

  belongs_to :user
  has_many :book_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end

end

app/models/book_comment.rb
class BookComment < ApplicationRecord

  validates :comment, presence: true

  belongs_to :user
  belongs_to :book
end

app/models/chat.rb
class Chat < ApplicationRecord
  belongs_to :user
  belongs_to :room

  validates :message, presence: true, length: { maximum: 140 }
end

app/models/favorite.rb
class Favorite < ApplicationRecord

  belongs_to :user
  belongs_to :book

  validates :user_id, uniqueness:{scope: :book_id}

end

app/models/group.rb
class Group < ApplicationRecord
  has_many :group_users, dependent: :destroy
  has_many :users, through: :group_users

  has_one_attached :image

  def get_group_image
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/group_image.jpg')
      image.attach(io: File.open(file_path), filename: 'group_image.jpg')
    end
    image
  end
end

app/models/group_user.rb
class GroupUser < ApplicationRecord
  belongs_to :user
  belongs_to :group
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :user_rooms, dependent: :destroy
  has_many :chats, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, uniqueness: true, length: { in: 2..20 }
  validates :introduction, length: { maximum: 50 }

  has_one_attached :image

  has_many :books, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  #フォロー機能
  #フォローしている
  has_many :follower, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :following, through: :follower, source: :followed
  #フォローされた
  has_many :followed, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :followers, through: :followed, source: :follower

  #グループ
  has_many :group_users, dependent: :destroy
  has_many :groups, through: :group_users

  has_one_attached :profile_image

  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [width, height]).processed
  end

  def follow_by?(user)
    following.include?(user)
  end

  def follow(user)
    unless self == user
      follower.create(followed_id: user.id)
    end
  end

  def unfollow(user)
    follower.find_by(followed_id: user.id).destroy
  end

end

app/models/user_room.rb
class UserRoom < ApplicationRecord
   belongs_to :user
   belongs_to :room
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def new
    @book = Book.new
  end

  def create
     @hon = Book.new(book_params)
     @hon.user_id = current_user.id

     if @hon.save
      flash[:notice] = "Book was successfully created."
      #@hon = book.new(book_params)
      redirect_to book_path(@hon.id)
     else
      #flash[:notice] = "失敗しちゃったよ"
      @books = Book.all.order(params[:sort])
      @book = Book.new
      render :index
     end
  end

  def index
    if params[:category].present?
      @books = Book.where(tag: params[:category])
    else
      @books = Book.all.order(params[:sort])
    end

    @book = Book.new
    @hon = Book.new #エラー用
  end

  def show
    @book = Book.find(params[:id])
    @book_user = @book.user
    #@books = Book.all
    @book_comment = BookComment.new
  end

  def edit
    is_match_login_user
    @book = Book.find(params[:id])
    @hon = Book.find(params[:id]) #エラー用
  end

  def update
    is_match_login_user
    @hon = Book.find(params[:id])

    if @hon.update(book_params)
      @book = Book.find(params[:id])
      flash[:notice] = "Book was successfully updated."
      redirect_to book_path(@book.id)
    else
      #flash[:notice] = "Book was not successfully updated"
      @book =  Book.find(params[:id])
      render :edit

    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy

    if @book.destroy
      flash[:notice] = "Book was successfully delete."
      redirect_to books_path
    else
      flash[:notice] = "消せなかったよ"
      redirect_to books_path
    end

  end

  private
    def book_params
      params.require(:book).permit(:title, :body, :image, :star, :tag)
    end

  def is_match_login_user
    book = Book.find(params[:id])
    unless book.user_id == current_user.id
      redirect_to "/books"
    end
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/chats_helper.rb
module ChatsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/group_users_helper.rb
module GroupUsersHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

    <script src="https://kit.fontawesome.com/d81676dda2.js" crossorigin="anonymous"></script>
    <!--グラフ作成-->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.9.3/Chart.min.js"></script>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <header class = "shadow-sm">
      <nav class = "navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">


              <a class = "navbar-brand" href="/">
                <span>Bookers</span>
              </a>

              <button class = "navbar-toggler" type = "button" data-toggle = "collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded = "false" aria-label = "Toggle navigation">
                <span class="navbar-toggler-icon"></span>
              </button>

                <div class = "collapse navbar-collapse" id="navbarNavDropdown">

                  <ul class="navbar-nav ml-auto">

                   <% if user_signed_in? %>

            <li class="nav-item text-white ml-2">
              <i class="fas fa-home"></i><%= link_to 'Home', user_path(current_user.id) , class: 'text-light'%>
            </li>
            <li class="nav-item text-white ml-2">
              <i class="fas fa-users"></i><%= link_to ' Users ', users_path , class: 'text-light'%>
            </li>
            <li class="nav-item text-white ml-2">
              <i class="fas fa-book-open"></i><%= link_to ' Books ', books_path , class: 'text-light'%>
            </li>
            <li class="nav-item text-white ml-2">
              <i class="fas fa-sign-out-alt"></i><%= link_to " Log out ", destroy_user_session_path, method: :delete , class: 'text-light'%>
            </li>



          <% else %>

             <li class="nav-item text-white ml-2">
              <i class="fas fa-home"></i><%= link_to 'Home', root_path , class: 'text-light' %>
            </li>
            <li class="nav-item text-white ml-2">
              <i class="fas fa-link"></i><%= link_to ' About ', home_about_path , class: 'text-light'%>
            </li>
            <li class="nav-item text-white ml-2">
              <i class="fas fa-user-plus"></i><%= link_to " Sign up ", new_user_registration_path , class: 'text-light'%>
            </li>
            <li class="nav-item text-white ml-2">
              <i class="fas fa-sign-in-alt"></i><%= link_to " Log in ", new_user_session_path , class: 'text-light'%>
            </li>

          <% end %>

            </ul>
            </div>

       </div>
      </nav>
    </header>


    <main>
      <p id="notice">
        <div class="message">
         <%= flash[:notice] %>
        </div>
      </p>
      <%= yield %>
    </main>



    <footer>
      <div class="container mt-5">
        <div class = "row">
          <div class = "mx-auto">
            <p>CopyRight Infratop.inc</p>
          </div>
        </div>
      </div>
    </footer>


  </body>
</html>